language: python
dist: xenial
sudo: required
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=4.0
matrix:
  exclude:
    - env: DJANGO=1.11
      python: "3.7"
    - env: DJANGO=1.11
      python: "3.8"
    - env: DJANGO=2.0
      python: "3.8"
    - env: DJANGO=2.1
      python: "3.8"
    - env: DJANGO=3.0
      python: "3.5"
addons:
  chrome: stable
  apt:
    packages:
    - enchant
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
install:
  - pip install -q codecov tox tox-travis
script: tox
after_success:
 - codecov
before_deploy:
  - pip install -q -r requirements-base.txt Sphinx
  - cd docs
  - make html
  - cd $TRAVIS_BUILD_DIR
deploy:
  - provider: pages
    local-dir: docs/_build/html
    github-token: $GH_TOKEN
    skip_cleanup: true
    on:
      branch: master
      python: "3.8"
      condition: $DJANGO = 2.2
  - provider: pypi
    skip_cleanup: true
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      python: "3.8"
      condition: $DJANGO = 2.2
notifications:
  email: false
